import {
  CHANNEL_SYSTEM_AUTHOR_ID,
  CommandId,
  projectOrchestrationOf,
  type CardActivity,
  type CardEvidenceItem,
  type CardFixRound,
  type CardId,
  type OrchestrationCard,
  type OrchestrationEvent,
  type OrchestrationReadModel,
  type PullRequestCheck,
  type PullRequestRef,
  type Reason,
} from "@iskra/contracts";
import { parseChangeRequestUrl } from "@iskra/shared/changeRequestUrl";
import { makeDrainableWorker } from "@iskra/shared/DrainableWorker";
import * as Cause from "effect/Cause";
import * as Context from "effect/Context";
import * as DateTime from "effect/DateTime";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Layer from "effect/Layer";
import * as Path from "effect/Path";
import * as Schedule from "effect/Schedule";
import type * as Scope from "effect/Scope";
import * as Stream from "effect/Stream";

import { ProjectionCardRepositoryLive } from "../persistence/Layers/ProjectionCards.ts";
import { ProjectionCardRepository } from "../persistence/Services/ProjectionCards.ts";
import { ProcessRunner } from "../processRunner.ts";
import { PullRequestService } from "../pullRequest/PullRequestService.ts";
import { forkParked } from "../serverActivation.ts";
import { SourceControlProviderRegistry } from "../sourceControl/SourceControlProviderRegistry.ts";
import { GitVcsDriver } from "../vcs/GitVcsDriver.ts";
import * as CardWorkspace from "./CardWorkspace.ts";
import * as OrchestrationEngine from "./Services/OrchestrationEngine.ts";
import * as ProjectionSnapshotQuery from "./Services/ProjectionSnapshotQuery.ts";

/**
 * Landing. A card entering review lands through a pull request when its project has a host
 * remote (or its policy says so), otherwise by a local fast-forward. The server pushes and opens
 * the pull request; agents never do. While the card is in review or landing its pull request is
 * polled: failing CI and trusted review comments go back to the owner as fix rounds, comments from
 * people without write access wait in Needs you, and a conflict sends the owner to rebase. A
 * person approving the merge makes the server merge; a merge on the host lands the card too. After
 * a card lands, what it blocked is freed and open cards touching the same exclusive paths are told
 * to rebase.
 */
export class CardLandingReactor extends Context.Service<
  CardLandingReactor,
  {
    readonly start: () => Effect.Effect<void, never, Scope.Scope>;
    /** Polls every pull request being landed now and waits for all queued work. */
    readonly pollNow: Effect.Effect<void>;
    readonly drain: Effect.Effect<void>;
  }
>()("@iskra/cli/orchestration/CardLandingReactor") {}

type LandingJob =
  | { readonly kind: "open"; readonly cardId: CardId }
  | { readonly kind: "land"; readonly cardId: CardId; readonly key: string }
  | { readonly kind: "poll" };

/** Collaborator permissions whose comments reach the owner without a person forwarding them. */
const TRUSTED_PERMISSIONS = new Set(["admin", "maintain", "write"]);
const PERMISSION_CACHE_MS = 60 * 60 * 1000;

/** The pull request a card links to, as PullRequestService reads it. */
export const pullRequestRefOf = (card: OrchestrationCard): PullRequestRef | null => {
  const link = card.landing?.url === undefined || card.landing.url === null ? null : parseChangeRequestUrl(card.landing.url);
  return link === null
    ? null
    : { projectId: card.projectId, host: link.host, repository: link.repository, number: link.number };
};

/** What a pull request says about the card's work: its acceptance criteria and evidence, as text. */
export function pullRequestBody(card: OrchestrationCard): string {
  const criteria = card.acceptance.criteria.map((criterion) => `- ${criterion.text}`).join("\n");
  const evidence = card.evidence;
  return [
    card.spec.trim(),
    criteria.length === 0 ? "" : `## Acceptance criteria\n\n${criteria}`,
    evidence === null
      ? ""
      : `## Evidence\n\nChecks ${evidence.passed ? "passed" : "failed"} on ${evidence.headSha.slice(0, 7)} (${evidence.checkCount} run).${evidence.flags.length === 0 ? "" : ` Flagged for a person: ${evidence.flags.map((flag) => `${flag.kind} ${flag.path}`).join(", ")}.`}`,
    `Card: ${card.title}`,
    "Generated by Iskra",
  ]
    .filter((part) => part.length > 0)
    .join("\n\n");
}

/** The failing host checks, as the owner reads them. */
export const failingChecks = (checks: ReadonlyArray<PullRequestCheck>) =>
  checks.filter((check) => check.status === "failure" || check.status === "cancelled");

const make = Effect.gen(function* () {
  const engine = yield* OrchestrationEngine.OrchestrationEngineService;
  const snapshotQuery = yield* ProjectionSnapshotQuery.ProjectionSnapshotQuery;
  const workspace = yield* CardWorkspace.CardWorkspace;
  const pullRequests = yield* PullRequestService;
  const sourceControl = yield* SourceControlProviderRegistry;
  const git = yield* GitVcsDriver;
  const runner = yield* ProcessRunner;
  const cards = yield* ProjectionCardRepository;
  const fileSystem = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const nowIso = Effect.map(DateTime.now, DateTime.formatIso);
  const nowMs = Effect.map(DateTime.now, DateTime.toEpochMillis);

  const readModel = () => snapshotQuery.getCommandReadModel();
  const cardIn = (model: OrchestrationReadModel, cardId: CardId) =>
    (model.cards ?? []).find((card) => card.id === cardId);

  /** An entry from Iskra in the card's activity; its id makes a repeated poll record it once. */
  const record = (
    cardId: CardId,
    activityId: string,
    entry: Pick<CardActivity, "kind" | "body" | "deliverTo"> &
      Partial<Pick<CardActivity, "author">> & { readonly reason: Reason },
  ) =>
    Effect.gen(function* () {
      yield* engine.dispatch({
        type: "card.activity.record",
        commandId: CommandId.make(`card-landing-activity:${activityId}`),
        activityId,
        cardId,
        author: { kind: "system", id: CHANNEL_SYSTEM_AUTHOR_ID },
        runThreadId: null,
        elicitation: null,
        answers: null,
        status: null,
        evidenceId: null,
        createdAt: yield* nowIso,
        ...entry,
      });
    });

  /**
   * Sends the card back to its owner with a fix round; once the project's rounds are used the
   * card pauses for a person instead.
   */
  const returnToWork = (card: OrchestrationCard, key: string, round: CardFixRound | null, reason: string) =>
    engine
      .dispatch({
        type: "card.work.return",
        commandId: CommandId.make(`card-landing-return:${key}`),
        cardId: card.id,
        reason,
        ...(round === null ? {} : { round }),
      })
      .pipe(
        Effect.asVoid,
        Effect.catchTag("OrchestrationCommandInvariantError", (refusal) =>
          round === null
            ? Effect.logWarning("card could not return to work", { cardId: card.id, detail: refusal.detail })
            : Effect.gen(function* () {
                if (card.status === "landing") {
                  yield* engine
                    .dispatch({
                      type: "card.merge.cancel",
                      commandId: CommandId.make(`card-landing-cancel:${key}`),
                      cardId: card.id,
                    })
                    .pipe(Effect.ignore);
                }
                yield* engine
                  .dispatch({
                    type: "card.pause.system",
                    commandId: CommandId.make(`card-landing-pause:${key}`),
                    cardId: card.id,
                    reason: { code: "fixRoundsExhausted", text: refusal.detail },
                  })
                  .pipe(Effect.ignore);
              }),
        ),
      );

  const tellBuilder = (cardId: CardId, activityId: string, code: string, body: string) =>
    record(cardId, activityId, {
      kind: "message",
      body,
      deliverTo: "builder",
      reason: { code, text: body.split("\n")[0]!.slice(0, 200) },
    });

  const openPullRequest = Effect.fn("CardLandingReactor.openPullRequest")(function* (cardId: CardId) {
    const model = yield* readModel();
    const card = cardIn(model, cardId);
    const project = model.projects.find((candidate) => candidate.id === card?.projectId);
    if (card === undefined || project === undefined || card.status !== "inReview" || card.landing !== null) {
      return;
    }
    const policy = projectOrchestrationOf(project);
    const linkedAt = yield* nowIso;
    const linkLocal = engine.dispatch({
      type: "card.landing.link",
      commandId: CommandId.make(`card-landing-link:local:${cardId}`),
      cardId,
      landing: { mode: "local", url: null, number: null, headSha: null, draft: false, linkedAt },
    });
    const wantsPullRequest =
      policy.landing === "pullRequest" ||
      (policy.landing === null && (project.repositoryIdentity?.provider ?? null) !== null);
    if (!wantsPullRequest || card.worktreePath === null || card.branch === null) {
      return yield* linkLocal;
    }
    const worktreePath = card.worktreePath;
    const branch = card.branch;
    const opened = yield* Effect.gen(function* () {
      const { baseBranch } = yield* workspace.projectFile(cardId);
      yield* git.pushCurrentBranch(worktreePath, branch);
      const provider = yield* sourceControl.resolve({ cwd: worktreePath });
      yield* Effect.scoped(
        Effect.gen(function* () {
          const directory = yield* fileSystem.makeTempDirectoryScoped({ prefix: "iskra-pr-body-" });
          const bodyFile = path.join(directory, "body.md");
          yield* fileSystem.writeFileString(bodyFile, pullRequestBody(card));
          yield* provider.createChangeRequest({
            cwd: worktreePath,
            baseRefName: baseBranch,
            headSelector: branch,
            title: card.title,
            bodyFile,
          });
        }),
      );
      const [created] = yield* provider.listChangeRequests({
        cwd: worktreePath,
        headSelector: branch,
        state: "open",
        limit: 1,
      });
      return created ?? null;
    }).pipe(
      Effect.catchCause((cause) =>
        Cause.hasInterruptsOnly(cause)
          ? Effect.failCause(cause)
          : Effect.succeed({ failed: Cause.pretty(cause).split("\n")[0] ?? "unknown error" }),
      ),
    );
    if (opened === null || "failed" in opened) {
      // Without a pull request the card still lands, locally.
      yield* record(cardId, `pr-open-failed:${cardId}`, {
        kind: "error",
        body: `The pull request couldn't be opened${opened === null ? "" : `: ${opened.failed}`}. The card will land by a local fast-forward instead.`,
        deliverTo: null,
        reason: { code: "pullRequestOpenFailed", text: "The pull request couldn't be opened." },
      });
      return yield* linkLocal;
    }
    yield* engine.dispatch({
      type: "card.landing.link",
      commandId: CommandId.make(`card-landing-link:pr:${cardId}:${opened.number}`),
      cardId,
      landing: {
        mode: "pullRequest",
        url: opened.url,
        number: opened.number,
        headSha: card.evidence?.headSha ?? null,
        draft: opened.isDraft ?? false,
        linkedAt,
      },
    });
  });

  /**
   * A plan child, or a card in a project with auto-merge on, lands without a person approving its
   * merge. The decider refuses anything else (see landingBeginRefusal); a refused card simply waits
   * for a person.
   */
  const beginLandingIfAllowed = Effect.fn("CardLandingReactor.beginLandingIfAllowed")(function* (
    cardId: CardId,
  ) {
    const model = yield* readModel();
    const card = cardIn(model, cardId);
    const project = model.projects.find((candidate) => candidate.id === card?.projectId);
    if (card === undefined || project === undefined || card.status !== "inReview") return;
    const parent = card.parentCardId === null ? undefined : cardIn(model, card.parentCardId);
    const reason =
      parent?.kind === "plan"
        ? ("planChild" as const)
        : projectOrchestrationOf(project).autoMerge.enabled
          ? ("autoMergePolicy" as const)
          : null;
    if (reason === null) return;
    yield* engine
      .dispatch({
        type: "card.landing.begin",
        commandId: CommandId.make(`card-landing-begin:${cardId}:${reason}:${card.evidence?.evidenceId ?? "none"}`),
        cardId,
        reason,
      })
      .pipe(
        Effect.catchTag("OrchestrationCommandInvariantError", (refusal) =>
          Effect.logInfo("card waits for a person to approve its merge", { cardId, detail: refusal.detail }),
        ),
      );
  });

  /** Frees what a landed card blocked and tells open cards touching its exclusive paths to rebase. */
  const afterLanding = Effect.fn("CardLandingReactor.afterLanding")(function* (
    landed: OrchestrationCard,
    files: ReadonlyArray<string>,
    key: string,
  ) {
    const model = yield* readModel();
    const project = model.projects.find((candidate) => candidate.id === landed.projectId);
    const others = (model.cards ?? []).filter(
      (card) => card.projectId === landed.projectId && card.id !== landed.id,
    );
    for (const blocked of others.filter((card) =>
      card.relations.some((relation) => relation.kind === "blockedBy" && relation.cardId === landed.id),
    )) {
      yield* engine.dispatch({
        type: "card.relation.remove",
        commandId: CommandId.make(`card-unblock:${key}:${blocked.id}`),
        cardId: blocked.id,
        kind: "blockedBy",
        otherCardId: landed.id,
      });
      yield* engine
        .dispatch({
          type: "card.relation.add",
          commandId: CommandId.make(`card-related:${key}:${blocked.id}`),
          cardId: blocked.id,
          kind: "related",
          otherCardId: landed.id,
        })
        .pipe(Effect.ignore);
    }
    if (project === undefined) return;
    const touched = CardWorkspace.exclusivePathConflicts(files, projectOrchestrationOf(project));
    if (touched.length === 0) return;
    const { baseRef } = yield* workspace.projectFile(landed.id);
    const open = yield* workspace.openCardChangedFiles(landed.projectId);
    for (const entry of open.filter((candidate) => candidate.cardId !== landed.id)) {
      const other = others.find((card) => card.id === entry.cardId);
      const shared = CardWorkspace.exclusivePathConflicts(entry.files, { exclusivePaths: touched });
      if (other === undefined || shared.length === 0) continue;
      const body = shared
        .map((path_) =>
          CardWorkspace.exclusivePathReturnMessage({ glob: path_.glob, baseRef, afterRebase: path_.afterRebase }),
        )
        .join("\n\n");
      yield* tellBuilder(other.id, `exclusive-path:${key}:${other.id}`, "exclusivePathChanged", body);
      if (other.status === "inReview" || other.status === "landing") {
        yield* returnToWork(other, `exclusive-path:${key}:${other.id}`, null, body.split("\n")[0]!);
      }
    }
  });

  /** Lands the card; a merge a person made on the host lands it straight from review. */
  const landCard = (card: OrchestrationCard, key: string, mergedOnHostUrl: string | null) =>
    engine.dispatch({
      type: "card.land",
      commandId: CommandId.make(`card-land:${key}`),
      cardId: card.id,
      ...(mergedOnHostUrl === null ? {} : { mergedOnHostUrl }),
    });

  const land = Effect.fn("CardLandingReactor.land")(function* (cardId: CardId, key: string) {
    const card = cardIn(yield* readModel(), cardId);
    if (card === undefined || card.status !== "landing") return;
    const ref = card.landing?.mode === "pullRequest" ? pullRequestRefOf(card) : null;
    if (ref !== null) {
      const merged = yield* pullRequests.runAction({ ...ref, action: "merge" }).pipe(
        Effect.as(null),
        Effect.catch((error) => Effect.succeed(error.message)),
      );
      if (merged !== null) {
        yield* record(cardId, `landing-blocked:${key}`, {
          kind: "error",
          body: `The host refused the merge: ${merged}`,
          deliverTo: null,
          reason: { code: "landingBlocked", text: "The host refused the merge." },
        });
        return yield* engine
          .dispatch({
            type: "card.merge.cancel",
            commandId: CommandId.make(`card-landing-cancel:${key}`),
            cardId,
          })
          .pipe(Effect.ignore);
      }
      yield* landCard(card, key, null);
      const files = yield* workspace.changedFiles(cardId).pipe(Effect.orElseSucceed(() => []));
      return yield* afterLanding(card, files, key);
    }
    const result = yield* workspace
      .land(cardId)
      .pipe(Effect.catch((error) => Effect.succeed({ kind: "notMerged" as const, message: error.message })));
    switch (result.kind) {
      case "landed":
        yield* landCard(card, key, null);
        return yield* afterLanding(card, result.files, key);
      case "conflict": {
        const body = `Landing stopped: rebasing onto \`${result.baseBranch}\` conflicts in ${result.files.join(", ") || "the worktree"}. Rebase, resolve the conflicts, commit, then call request_review again.`;
        yield* tellBuilder(cardId, `landing-conflict:${key}`, "rebaseConflict", body);
        return yield* returnToWork(card, key, "ci", `Rebasing onto ${result.baseBranch} conflicts.`);
      }
      case "checksFailed": {
        const body = `Landing stopped: the checks failed after rebasing.\n\n${result.summary}`;
        yield* tellBuilder(cardId, `landing-checks:${key}`, "checksFailed", body);
        return yield* returnToWork(card, key, "ci", "The checks failed while landing.");
      }
      case "notMerged":
        yield* record(cardId, `landing-blocked:${key}`, {
          kind: "error",
          body: `Landing stopped: ${result.message}`,
          deliverTo: null,
          reason: { code: "landingBlocked", text: "The card couldn't be merged into its base." },
        });
        return yield* engine
          .dispatch({ type: "card.merge.cancel", commandId: CommandId.make(`card-landing-cancel:${key}`), cardId })
          .pipe(Effect.ignore);
    }
  });

  // ponytail: asks gh with the machine's own login, not PullRequestService's pinned routing
  // credential; route through that credential if one server serves several GitHub accounts.
  const permissions = new Map<string, { readonly trusted: boolean; readonly at: number }>();
  const isTrusted = Effect.fn("CardLandingReactor.isTrusted")(function* (
    cwd: string,
    ref: PullRequestRef,
    login: string,
  ) {
    const hostName = ref.host ?? "";
    const key = `${hostName}/${ref.repository}:${login}`.toLowerCase();
    const now = yield* nowMs;
    const cached = permissions.get(key);
    if (cached !== undefined && now - cached.at < PERMISSION_CACHE_MS) return cached.trusted;
    const gh = (args: ReadonlyArray<string>) =>
      runner
        .run({ command: "gh", args, cwd, timeout: "30 seconds" })
        .pipe(
          Effect.map((output) => (output.code === 0 ? output.stdout.trim() : null)),
          Effect.orElseSucceed(() => null),
        );
    const permission = hostName.endsWith("github.com")
      ? yield* gh(["api", `repos/${ref.repository}/collaborators/${login}/permission`, "--jq", ".permission"])
      : null;
    // A host that can't say trusts only the account Iskra itself is signed in as.
    const trusted =
      permission !== null
        ? TRUSTED_PERMISSIONS.has(permission)
        : (yield* gh(["api", "user", "--jq", ".login"]))?.toLowerCase() === login.toLowerCase();
    permissions.set(key, { trusted, at: now });
    return trusted;
  });

  const pollCard = Effect.fn("CardLandingReactor.pollCard")(function* (card: OrchestrationCard, cwd: string) {
    const ref = pullRequestRefOf(card);
    if (ref === null || card.landing === null) return;
    const detail = yield* pullRequests.detail(ref);
    const head = card.evidence?.headSha ?? "unknown";

    if (detail.state === "merged") {
      // A person merging on the host is their approval.
      yield* landCard(card, `host-merge:${card.id}`, card.status === "inReview" ? detail.url : null);
      const files = yield* workspace.changedFiles(card.id).pipe(Effect.orElseSucceed(() => []));
      return yield* afterLanding(card, files, `host-merge:${card.id}`);
    }
    if (detail.state === "closed") {
      return yield* record(card.id, `pr-closed:${card.id}:${detail.number}`, {
        kind: "error",
        body: `The pull request was closed without merging: ${detail.url}`,
        deliverTo: null,
        reason: { code: "pullRequestClosed", text: "The pull request was closed without merging." },
      });
    }

    // CI-sourced checks become evidence once the host has a result for every one of them.
    const project = (yield* readModel()).projects.find((candidate) => candidate.id === card.projectId);
    const { checks } = yield* workspace.projectFile(card.id);
    const ciChecks = checks.filter((check) => check.source !== "local" && check.ciName !== null);
    const hostChecks = ciChecks.map((check) => ({
      check,
      host: detail.checks.find((candidate) => candidate.name === check.ciName),
    }));
    if (
      project !== undefined &&
      card.evidence !== null &&
      hostChecks.length > 0 &&
      hostChecks.every((entry) => entry.host !== undefined && entry.host.status !== "pending")
    ) {
      const evidenceId = `evidence-ci-${card.id}-${head}`;
      if (card.evidence.evidenceId !== evidenceId) {
        const local = yield* cards
          .listEvidenceItems({ cardId: card.id, evidenceId: card.evidence.evidenceId })
          .pipe(Effect.orElseSucceed(() => []));
        const items: Array<CardEvidenceItem> = [
          ...local.map(({ evidenceId: _e, cardId: _c, headSha: _h, purpose: _p, createdAt: _t, ...item }) => item),
          ...hostChecks.map(({ check, host }) => ({
            itemId: `ci:${check.id}`,
            kind: "check" as const,
            source: "ci" as const,
            name: check.name,
            criterionId: null,
            exitCode: host!.status === "success" || host!.status === "skipped" || host!.status === "neutral" ? 0 : 1,
            timedOut: false,
            durationMs: null,
            logTail: host!.description ?? "",
            artifactPath: host!.url,
            unavailable: null,
          })),
        ];
        yield* engine
          .dispatch({
            type: "card.evidence.record",
            commandId: CommandId.make(`card-evidence:${evidenceId}`),
            cardId: card.id,
            evidenceId,
            headSha: card.evidence.headSha,
            purpose: "review",
            items,
            flags: card.evidence.flags,
            risks: null,
            recordedAt: yield* nowIso,
          })
          .pipe(Effect.ignore);
      }
    }

    const failing = failingChecks(detail.checks);
    if (failing.length > 0) {
      const names = failing.map((check) => check.name).join(", ");
      yield* tellBuilder(
        card.id,
        `pr-ci-failed:${card.id}:${head}:${names}`,
        "ciFailed",
        [
          `CI failed on the pull request: ${names}. Fix it, commit, then call request_review again.`,
          ...failing.map((check) => `- ${check.name}: ${check.description ?? check.status}${check.url === null ? "" : ` (${check.url})`}`),
        ].join("\n"),
      );
      return yield* returnToWork(card, `pr-ci-failed:${card.id}:${head}`, "ci", `CI failed: ${names}.`);
    }
    if (detail.mergeability === "conflicting") {
      const { baseRef } = yield* workspace.projectFile(card.id);
      yield* tellBuilder(
        card.id,
        `pr-conflict:${card.id}:${head}`,
        "rebaseConflict",
        `The pull request conflicts with its base. Rebase onto ${baseRef}, resolve the conflicts, commit, then call request_review again.`,
      );
      return yield* returnToWork(card, `pr-conflict:${card.id}:${head}`, "ci", "The pull request conflicts with its base.");
    }

    const activity = yield* pullRequests.activity(ref);
    const remarks = [
      ...activity.comments.map((comment) => ({ id: comment.id, author: comment.author, body: comment.body, createdAt: comment.createdAt, url: comment.url })),
      ...activity.reviewThreads
        .filter((thread) => !thread.isResolved)
        .flatMap((thread) => thread.comments.map((comment) => ({ ...comment, body: `${thread.path}: ${comment.body}` }))),
    ].filter(
      (remark) => remark.author !== null && remark.body.trim().length > 0 && remark.createdAt > card.landing!.linkedAt,
    );
    let trustedKey: string | null = null;
    for (const remark of remarks) {
      const login = remark.author!.login;
      const body = `${login} on the pull request: ${remark.body}${remark.url === null ? "" : `\n${remark.url}`}`;
      if (yield* isTrusted(cwd, ref, login)) {
        yield* record(card.id, `pr-comment:${remark.id}`, {
          kind: "message",
          body,
          deliverTo: "builder",
          author: { kind: "github", id: login, trusted: true },
          reason: { code: "reviewComment", text: `${login} commented on the pull request.` },
        });
        trustedKey = remark.id;
      } else {
        // Shown on the card for a person to forward; the owner never reads it unasked.
        yield* record(card.id, `pr-comment:${remark.id}`, {
          kind: "message",
          body,
          deliverTo: null,
          author: { kind: "github", id: login, trusted: false },
          reason: { code: "untrustedComment", text: `${login} can't direct work on this repository; forward it if it should.` },
        });
      }
    }
    if (trustedKey !== null && card.status === "inReview") {
      yield* returnToWork(card, `pr-review:${card.id}:${trustedKey}`, "review", "Review comments on the pull request.");
    }
  });

  const poll = Effect.fn("CardLandingReactor.poll")(function* () {
    const model = yield* readModel();
    for (const card of model.cards ?? []) {
      if ((card.status !== "inReview" && card.status !== "landing") || card.landing?.mode !== "pullRequest") continue;
      const project = model.projects.find((candidate) => candidate.id === card.projectId);
      if (project === undefined) continue;
      yield* pollCard(card, card.worktreePath ?? project.workspaceRoot).pipe(
        Effect.catchCause((cause) =>
          Cause.hasInterruptsOnly(cause)
            ? Effect.failCause(cause)
            : Effect.logWarning("card pull request poll failed", { cardId: card.id, cause: Cause.pretty(cause) }),
        ),
      );
    }
  });

  const guarded =
    (kind: LandingJob["kind"]) =>
    <E>(effect: Effect.Effect<void, E>): Effect.Effect<void> =>
      effect.pipe(
        Effect.catchCause((cause) =>
          Cause.hasInterruptsOnly(cause)
            ? Effect.failCause(cause as Cause.Cause<never>)
            : Effect.logWarning("card landing job failed", { kind, cause: Cause.pretty(cause) }),
        ),
      );

  const worker = yield* makeDrainableWorker((job: LandingJob) =>
    job.kind === "open"
      ? guarded(job.kind)(
          openPullRequest(job.cardId).pipe(Effect.andThen(beginLandingIfAllowed(job.cardId))),
        )
      : job.kind === "land"
        ? guarded(job.kind)(land(job.cardId, job.key))
        : guarded(job.kind)(poll()),
  );

  const processEvent = (event: OrchestrationEvent) => {
    if (event.type !== "card.status-changed") return Effect.void;
    switch (event.payload.to) {
      case "inReview":
        return worker.enqueue({ kind: "open", cardId: event.payload.cardId });
      case "landing":
        return worker.enqueue({ kind: "land", cardId: event.payload.cardId, key: event.eventId });
      default:
        return Effect.void;
    }
  };

  const start = Effect.fn("CardLandingReactor.start")(function* () {
    const events = yield* engine.subscribeDomainEvents;
    yield* forkParked(Stream.runForEach(events, processEvent));
    // ponytail: one pass a minute over every card being landed; back off per card when host rate
    // limits start refusing the reads.
    yield* forkParked(
      worker.enqueue({ kind: "poll" }).pipe(
        Effect.andThen(worker.drain),
        Effect.repeat(Schedule.spaced("1 minute")),
        Effect.asVoid,
      ),
    );
  });

  return {
    start,
    pollNow: worker.enqueue({ kind: "poll" }).pipe(Effect.andThen(worker.drain)),
    drain: worker.drain,
  } satisfies CardLandingReactor["Service"];
});

export const layer = Layer.effect(CardLandingReactor, make).pipe(
  Layer.provide(ProjectionCardRepositoryLive),
);
