import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  AgentCreatedPayload as ContractsAgentCreatedPayloadSchema,
  AgentUpdatedPayload as ContractsAgentUpdatedPayloadSchema,
  AgentArchivedPayload as ContractsAgentArchivedPayloadSchema,
  AgentUnarchivedPayload as ContractsAgentUnarchivedPayloadSchema,
  CardCreatedPayload as ContractsCardCreatedPayloadSchema,
  CardUpdatedPayload as ContractsCardUpdatedPayloadSchema,
  CardStatusChangedPayload as ContractsCardStatusChangedPayloadSchema,
  CardDelegateChangedPayload as ContractsCardDelegateChangedPayloadSchema,
  CardRelationAddedPayload as ContractsCardRelationAddedPayloadSchema,
  CardRelationRemovedPayload as ContractsCardRelationRemovedPayloadSchema,
  CardDecisionRecordedPayload as ContractsCardDecisionRecordedPayloadSchema,
  CardWorkspaceSetPayload as ContractsCardWorkspaceSetPayloadSchema,
  CardWorkspaceClearedPayload as ContractsCardWorkspaceClearedPayloadSchema,
  ChannelCreatedPayload as ContractsChannelCreatedPayloadSchema,
  ChannelUpdatedPayload as ContractsChannelUpdatedPayloadSchema,
  ChannelArchivedPayload as ContractsChannelArchivedPayloadSchema,
  ChannelUnarchivedPayload as ContractsChannelUnarchivedPayloadSchema,
  ChannelRunStartedPayload as ContractsChannelRunStartedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadPinnedPayload as ContractsThreadPinnedPayloadSchema,
  ThreadUnpinnedPayload as ContractsThreadUnpinnedPayloadSchema,
  ThreadPinReorderedPayload as ContractsThreadPinReorderedPayloadSchema,
  ThreadPullRequestLinkedPayload as ContractsThreadPullRequestLinkedPayloadSchema,
  ThreadPullRequestUnlinkedPayload as ContractsThreadPullRequestUnlinkedPayloadSchema,
  ThreadPullRequestSyncedPayload as ContractsThreadPullRequestSyncedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@iskra/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const AgentCreatedPayload = ContractsAgentCreatedPayloadSchema;
export const AgentUpdatedPayload = ContractsAgentUpdatedPayloadSchema;
export const AgentArchivedPayload = ContractsAgentArchivedPayloadSchema;
export const AgentUnarchivedPayload = ContractsAgentUnarchivedPayloadSchema;

export const CardCreatedPayload = ContractsCardCreatedPayloadSchema;
export const CardUpdatedPayload = ContractsCardUpdatedPayloadSchema;
export const CardStatusChangedPayload = ContractsCardStatusChangedPayloadSchema;
export const CardDelegateChangedPayload = ContractsCardDelegateChangedPayloadSchema;
export const CardRelationAddedPayload = ContractsCardRelationAddedPayloadSchema;
export const CardRelationRemovedPayload = ContractsCardRelationRemovedPayloadSchema;
export const CardDecisionRecordedPayload = ContractsCardDecisionRecordedPayloadSchema;
export const CardWorkspaceSetPayload = ContractsCardWorkspaceSetPayloadSchema;
export const CardWorkspaceClearedPayload = ContractsCardWorkspaceClearedPayloadSchema;

export const ChannelCreatedPayload = ContractsChannelCreatedPayloadSchema;
export const ChannelUpdatedPayload = ContractsChannelUpdatedPayloadSchema;
export const ChannelArchivedPayload = ContractsChannelArchivedPayloadSchema;
export const ChannelUnarchivedPayload = ContractsChannelUnarchivedPayloadSchema;
export const ChannelRunStartedPayload = ContractsChannelRunStartedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;
export const ThreadPinnedPayload = ContractsThreadPinnedPayloadSchema;
export const ThreadUnpinnedPayload = ContractsThreadUnpinnedPayloadSchema;
export const ThreadPinReorderedPayload = ContractsThreadPinReorderedPayloadSchema;
export const ThreadPullRequestLinkedPayload = ContractsThreadPullRequestLinkedPayloadSchema;
export const ThreadPullRequestUnlinkedPayload = ContractsThreadPullRequestUnlinkedPayloadSchema;
export const ThreadPullRequestSyncedPayload = ContractsThreadPullRequestSyncedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
